### ISSUE TITLE
hello, 可以提供查重和小作文公共 api 么，如果人力不够可以协助开发

### ISSUE THREAD

**Issue by Shimada666** [ASoulCnki/ASoulCnkiBackend#15]

**Comment by Shimada666** [comment]
预想api
* 随机获得一篇小作文
* 查重（输入数据，返回查重结果）

**Comment by stream2000** [comment]
目前查重api已经开放了 可以看一下api文档捏。随机小作文目前还没有做，老哥可以想一个cost低的方式做一下，直接提pr就好

**Comment by ch3cknull** [comment]
目前查重接口已有：
## 查重API
接口地址：https://asoulcnki.asia/v1/api/check
请求方式：POST
Content-Type: application/json
请求内容
```json
{
    "text":"待查重内容，字数10-1000之间"
}
```

**Comment by ch3cknull** [comment]
> 预想api
> 
> * 随机获得一篇小作文
> * 查重（输入数据，返回查重结果）

接口文档已更新，现提供**查重API**和**作文展API**（可根据**关键词**，**动态（非评论）发布者** 等条件筛选小作文，但是**没有随机**）
https://github.com/ASoulCnki/ASoulCnkiBackend/blob/master/api.md

**Comment by Shimada666** [comment]
> > 预想api
> > 
> > * 随机获得一篇小作文
> > * 查重（输入数据，返回查重结果）
> 
> 接口文档已更新，现提供**查重API**和**作文展API**（可根据**关键词**，**动态（非评论）发布者** 等条件筛选小作文，但是**没有随机**）
> https://github.com/ASoulCnki/ASoulCnkiBackend/blob/master/api.md

太牛了捏 谢谢嘉人们

**Comment by Shimada666** [comment]
> > > > 预想api
> > > > 
> > > > * 随机获得一篇小作文
> > > > * 查重（输入数据，返回查重结果）
> > > 
> > > 
> > > 接口文档已更新，现提供**查重API**和**作文展API**（可根据**关键词**，**动态（非评论）发布者** 等条件筛选小作文，但是**没有随机**）
> > > https://github.com/ASoulCnki/ASoulCnkiBackend/blob/master/api.md
> > 
> > 
> > 太牛了捏 谢谢嘉人们
> 
> 还有其他问题吗，没有的话我就关掉这个issue了哈

好滴 关掉吧
