### ISSUE TITLE
hi 我想参与开发，请问怎么才能拿到开发所用 json 捏

### ISSUE THREAD

**Issue by Shimada666** [ASoulCnki/ASoulCnkiBackend#19]
我邮箱是 649940882@qq.com，可以发一份嘛，另外请问 readme 的 secure.key 是什么东西捏，怎么获得

**Comment by stream2000** [comment]
https://drive.google.com/file/d/151oz560vj2T2uwxYrRbxq1NPYwvx_dNf/view?usp=sharing

这里是一份很早期的数据文件了，甚至有些列是丢失的，我们最近应该会更新下，issue可以保持开启，我们更新到google drive以后再通知你捏

**Comment by stream2000** [comment]
secure key的话，是你自己配置的，在application.yml里，相当于是管理员账号了，用来给一些api鉴权用的，因为目前系统比较简单就采用了这种非常原始的鉴权方式。

**Comment by yllhwa** [comment]
> https://drive.google.com/file/d/151oz560vj2T2uwxYrRbxq1NPYwvx_dNf/view?usp=sharing
> 
> 这里是一份很早期的数据文件了，甚至有些列是丢失的，我们最近应该会更新下，issue可以保持开启，我们更新到google drive以后再通知你捏

刚更新了这个文件了，可以直接用

**Comment by Shimada666** [comment]
> > https://drive.google.com/file/d/151oz560vj2T2uwxYrRbxq1NPYwvx_dNf/view?usp=sharing
> > 这里是一份很早期的数据文件了，甚至有些列是丢失的，我们最近应该会更新下，issue可以保持开启，我们更新到google drive以后再通知你捏
> 
> 刚更新了这个文件了，可以直接用

好滴 我测试一下 谢谢

**Comment by stream2000** [comment]
这个issue我关了哈
