### ISSUE TITLE
json数据文件请求

### ISSUE THREAD

**Issue by Misaka17032** [ASoulCnki/ASoulCnkiBackend#4]
请问是否能够公开json数据？
谢谢au了（

**Comment by stream2000** [comment]
有一份比较早期的数据可以公开： https://drive.google.com/file/d/151oz560vj2T2uwxYrRbxq1NPYwvx_dNf/view?usp=sharing


顺便问一下，需要评论数据是为了枝网相关的开发，还是有其他的处理评论的需求？

**Comment by Misaka17032** [comment]
谢谢！
不算是做枝网相关，是为了做数据处理，大概是关于文本生成的（试图生成发病文字）
